name: hestia-uber-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - ld_impl_linux-64=2.39
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.7
  - pip=22.3.1
  - python=3.11.0
  - readline=8.1.2
  - setuptools=65.5.1
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.2.1
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cffi==1.15.1
    - debugpy==1.6.4
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - geographiclib==2.0
    - geopy==2.3.0
    - idna==3.4
    - ipykernel==6.17.1
    - ipython==8.7.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==7.4.8
    - jupyter-console==6.4.4
    - jupyter-core==5.1.0
    - jupyter-server==1.23.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - nbclassic==0.4.8
    - nbclient==0.7.2
    - nbconvert==7.2.6
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.23.5
    - openpyxl==3.0.10
    - packaging==21.3
    - pandas==1.5.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.5.4
    - portion==2.3.0
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.33
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pyexcelerate==0.10.0
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyperclip==1.8.2
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyzmq==24.0.1
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - send2trash==1.8.0
    - six==1.16.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.2
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tornado==6.2
    - traitlets==5.6.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - widgetsnbextension==4.0.3
